using CATHODE.Scripting;
using CATHODE.Scripting.Internal;
using CathodeLib;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.ComTypes;
using System.Threading.Tasks;
using CATHODE.Scripting.Internal.Parsers;
using System.Runtime.CompilerServices;




#if UNITY_EDITOR || UNITY_STANDALONE_WIN
using UnityEngine;
#elif GODOT
using Godot;
using System.Numerics;
using Matrix4x4 = System.Numerics.Matrix4x4;
using Quaternion = System.Numerics.Quaternion;
using Vector2 = Godot.Vector2;
using Vector3 = Godot.Vector3;
using Vector4 = Godot.Vector4;
using Color = Godot.Color;
#else
using System.Numerics;
#endif

namespace CATHODE
{
    /// <summary>
    /// DATA/ENV/x/WORLD/COMMANDS.PAK
    /// </summary>
    public class Commands : CathodeFile
    {
        public List<Composite> Entries = new List<Composite>();
        public static new Implementation Implementation = Implementation.CREATE | Implementation.LOAD | Implementation.SAVE;

        protected override bool HandlesLoadingManually => true;
        private EnvironmentAnimations _envAnims;
        private CollisionMaps _colMaps;
        private RenderableElements _reds;
        private HavokPackfile _physicsHKX;
        private Textures _textures;
        private Textures _globalTextures;

        public bool Compressed { get { return _compressed; } set { _compressed = value; } }
        private bool _compressed = false;

        public Commands(string path, EnvironmentAnimations envAnims, CollisionMaps colMaps, RenderableElements reds, HavokPackfile physicsHKX = null, Textures textures = null, Textures globalTextures = null) : base(path)
        {
            _envAnims = envAnims;
            _colMaps = colMaps;
            _reds = reds;
            _physicsHKX = physicsHKX;
            _textures = textures;
            _globalTextures = globalTextures;

            Utils = new CommandsUtils(this);

            _loaded = Load();

            //Double check to ensure any new guids loaded in are stored - can definitely handle this nicer.
            switch  (Path.GetExtension(_filepath).ToUpper())
            {
                case ".BIN":
                case ".GZ":
                    foreach (var others in CommandsBIN.ParameterNames)
                        ShortGuidUtils.Generate(others.Value);
                    break;
            }
        }

        public void ClearReferences()
        {
            _envAnims = null;
            _colMaps = null;
            _reds = null;
            _physicsHKX = null;
            _textures = null;
            _globalTextures = null;
        }

        ~Commands()
        {
            ClearReferences();
            Entries.Clear();
        }

        // This is always size of 3, in the order:
        //  - Root Instance (the map's entry composite, usually containing entities that call mission/environment composites)
        //  - Global Instance (the main data handler for keeping track of mission number, etc - kinda like a big singleton)
        //  - Pause Menu Instance
        private ShortGuid[] _entryPoints = null;
        private Composite[] _entryPointObjects = null;

        /// <summary>
        /// Use this to access various utilities for dealing with Commands data.
        /// Additional metadata generated by these utils will write to your Commands file when saved.
        /// </summary>
        public readonly CommandsUtils Utils;

        #region FILE_IO
        override protected bool LoadInternal(MemoryStream stream)
        {
            _compressed = _filepath != null && _filepath != "" && Path.GetExtension(_filepath).ToLower() == ".gz";

            switch (Path.GetExtension(_filepath).ToUpper())
            {
                case ".PAK":
                    CommandsPAK.Read(stream, out _entryPoints, out Entries, _envAnims, _colMaps, _reds, _physicsHKX);
                    break;
                case ".GZ":
                case ".BIN":
                    CommandsBIN.Read(_compressed ? Utilities.GZIPDecompress(stream) : stream, out _entryPoints, out Entries, _envAnims, _colMaps, _reds, _physicsHKX);
                    break;
                default:
                    return false;
            }

            return true;
        }

        override protected bool SaveInternal()
        {
            //Validate entry points and composite count
            if (Entries.Count == 0) return false;
            if (_entryPoints == null) _entryPoints = new ShortGuid[3];

            if (_compressed && Path.GetExtension(_filepath).ToLower() != ".gz")
                _filepath += ".gz";
            else if (!_compressed && Path.GetExtension(_filepath).ToLower() == ".gz")
                _filepath = _filepath.Substring(0, _filepath.Length - 3);

            #region FIX_POTENTIAL_ERRORS
            //If we have composites but the entry points are broken, correct them first!
            if (GetComposite(_entryPoints[2]) == null)
            {
                Composite pausemenu = GetComposite("PAUSEMENU");
                if (pausemenu == null)
                {
                    Console.WriteLine("WARNING: PAUSEMENU composite does not exist! Creating blank placeholder.");
                    pausemenu = AddComposite("PAUSEMENU");
                    pausemenu.shortGUID = new ShortGuid("FE-7B-FE-B3");
                }
                _entryPoints[2] = pausemenu.shortGUID;
            }
            if (GetComposite(_entryPoints[1]) == null)
            {
                Composite global = GetComposite("GLOBAL");
                if (global == null)
                {
                    Console.WriteLine("WARNING: GLOBAL composite does not exist! Creating blank placeholder. This may cause issues with GLOBAL references.");
                    global = AddComposite("GLOBAL");
                    global.shortGUID = new ShortGuid("1D-2E-CE-E5");
                }
                _entryPoints[1] = global.shortGUID;
            }
            if (GetComposite(_entryPoints[0]) == null)
            {
                Console.WriteLine("WARNING: Entry point was not set! Defaulting to composite at index zero.");
                _entryPoints[0] = Entries[0].shortGUID;
            }

            SyncDerivedResourceParameters();
            RefreshEntryPointObjects();

            //Fix (& verify) entity-attached resource info
            Parallel.For(0, Entries.Count, i =>
            {
                var functions = Entries[i].functions_dictionary.Values;
                Parallel.ForEach(functions, function =>
                {
                    if (function.function.IsFunctionType)
                    {
                        switch (function.function.AsFunctionType)
                        {
                            case FunctionType.TRAV_1ShotClimbUnder:
                            case FunctionType.TRAV_1ShotFloorVentEntrance:
                            case FunctionType.TRAV_1ShotFloorVentExit:
                            case FunctionType.TRAV_1ShotLeap:
                            case FunctionType.TRAV_1ShotSpline:
                            case FunctionType.TRAV_1ShotVentEntrance:
                            case FunctionType.TRAV_1ShotVentExit:
                            case FunctionType.TRAV_ContinuousBalanceBeam:
                            case FunctionType.TRAV_ContinuousCinematicSidle:
                            case FunctionType.TRAV_ContinuousClimbingWall:
                            case FunctionType.TRAV_ContinuousLadder:
                            case FunctionType.TRAV_ContinuousLedge:
                            case FunctionType.TRAV_ContinuousPipe:
                            case FunctionType.TRAV_ContinuousTightGap:
                                function.AddResource(ResourceType.TRAVERSAL_SEGMENT);
                                break;
                            case FunctionType.NavMeshBarrier:
                                function.AddResource(ResourceType.NAV_MESH_BARRIER_RESOURCE);
                                break;
                            case FunctionType.ExclusiveMaster:
                                function.AddResource(ResourceType.EXCLUSIVE_MASTER_STATE_RESOURCE);
                                break;

                            //NOTE: Really, DYNAMIC_PHYSICS_SYSTEM isn't actually on the entity, it's on the composite
                            case FunctionType.PhysicsSystem:
                                ResourceReference physSystem = function.AddResource(ResourceType.DYNAMIC_PHYSICS_SYSTEM);
                                if (physSystem.PhysicsSystem != null)
                                {
                                    physSystem.PhysicsSystemIndex = physSystem.PhysicsSystem.SystemIndex;
                                }
                                else
                                {
                                    Parameter dps_index = function.GetParameter(ShortGuids.system_index);
                                    int systemIndex = (dps_index?.content is cInteger idx) ? idx.value : 0;
                                    physSystem.PhysicsSystem = _physicsHKX?.GetPhysicsSystem(systemIndex);
                                    physSystem.PhysicsSystemIndex = systemIndex;
                                }
                                SyncPhysicsSystemIndexParameter(function);
                                Parameter position = function.GetParameter("position");
                                if (position?.content?.dataType == DataType.TRANSFORM)
                                {
                                    cTransform transform = (cTransform)position.content;
                                    physSystem.position = transform.position;
                                    physSystem.rotation = transform.rotation;
                                }
                                else
                                {
                                    physSystem.position = new Vector3(0, 0, 0);
                                    physSystem.rotation = new Vector3(0, 0, 0);
                                }
                                break;

                            case FunctionType.EnvironmentModelReference:
                                Parameter rsc = function.GetParameter("resource");
                                if (rsc == null)
                                {
                                    rsc = new Parameter("resource", new cResource(function.shortGUID));
                                    function.parameters.Add(rsc);
                                }
                                cResource rsc_p = (cResource)rsc.content;
                                rsc_p.AddResource(ResourceType.ANIMATED_MODEL);
                                break;
                            case FunctionType.ModelReference:
                                Parameter mdl = function.GetParameter("resource");
                                if (mdl == null)
                                {
                                    mdl = new Parameter("resource", new cResource(function.shortGUID));
                                    function.parameters.Add(mdl);
                                }
                                break;
                        }
                    }
                });
            });
            #endregion

            byte[] content = null;
            switch (Path.GetExtension(_filepath).ToUpper())
            {
                case ".PAK":
                    CommandsPAK.Write(_entryPoints, Entries, out content, _envAnims, _colMaps, _reds);
                    break;
                case ".GZ":
                case ".BIN":
                    CommandsBIN.Write(_entryPoints, Entries, out content, _envAnims, _colMaps, _reds);
                    break;
                default:
                    return false;
            }

            WriteToDisk(_filepath, content);

            if (_compressed)
                Utilities.GZIPCompress(_filepath);
            else
                SaveSibling();

            return true;
        }

        /// <summary>
        /// Write the same script data out in the other of the two formats a level carries.
        /// </summary>
        private void SaveSibling()
        {
            string siblingPath;
            byte[] siblingContent;

            switch (Path.GetExtension(_filepath).ToUpper())
            {
                case ".PAK":
                    siblingPath = Path.ChangeExtension(_filepath, ".BIN");
                    CommandsBIN.Write(_entryPoints, Entries, out siblingContent, _envAnims, _colMaps, _reds);
                    break;
                case ".BIN":
                    siblingPath = Path.ChangeExtension(_filepath, ".PAK");
                    CommandsPAK.Write(_entryPoints, Entries, out siblingContent, _envAnims, _colMaps, _reds);
                    break;
                default:
                    return;
            }

            WriteToDisk(siblingPath, siblingContent);
        }

        private static void WriteToDisk(string path, byte[] content)
        {
            using (Stream stream = File.OpenWrite(path))
            using (BinaryWriter writer = new BinaryWriter(stream))
            {
                writer.BaseStream.SetLength(0);
                writer.Write(content);
            }
        }
        #endregion

        #region ACCESSORS
        /// <summary>
        /// Add a new composite
        /// </summary>
        public Composite AddComposite(string name, bool isRoot = false)
        {
            Composite comp = new Composite(name);
            Entries.Add(comp);
            if (isRoot) SetRootComposite(comp);
            return comp;
        }

        /// <summary>
        /// Return a list of filenames for composites in the CommandsPAK archive
        /// </summary>
        public string[] GetCompositeNames()
        {
            string[] toReturn = new string[Entries.Count];
            for (int i = 0; i < Entries.Count; i++) toReturn[i] = Entries[i].name;
            return toReturn;
        }

        /// <summary>
        /// Get an individual composite
        /// </summary>
        public Composite GetComposite(string name)
        {
            return Entries.FirstOrDefault(o => o != null && o.name == name || o.name == name.Replace('/', '\\'));
        }
        public Composite GetComposite(ShortGuid id)
        {
            return Entries.FirstOrDefault(o => o != null && o.shortGUID == id);
        }

        /// <summary>
        /// Get entry point composite objects
        /// </summary>
        public Composite[] EntryPoints
        {
            get
            {
                if (_entryPoints == null) return null;
                if (_entryPointObjects != null) return _entryPointObjects;
                RefreshEntryPointObjects();
                return _entryPointObjects;
            }
        }

        /// <summary>
        /// Set the root composite for this COMMANDS.PAK (the root of the level - GLOBAL and PAUSEMENU are also instanced)
        /// </summary>
        public void SetRootComposite(Composite composite)
        {
            SetRootComposite(composite.shortGUID);
        }
        public void SetRootComposite(ShortGuid compositeID)
        {
            if (_entryPoints == null)
                _entryPoints = new ShortGuid[3];

            _entryPoints[0] = compositeID;
            _entryPointObjects = null;
        }
        #endregion

        #region HELPERS

        /// <summary>
        /// Refresh the composite pointers for our entry points
        /// </summary>
        private void RefreshEntryPointObjects()
        {
            _entryPointObjects = new Composite[_entryPoints.Length];
            for (int i = 0; i < _entryPoints.Length; i++) _entryPointObjects[i] = GetComposite(_entryPoints[i]);
        }

        /// <summary>
        /// Test Stuff
        /// </summary>
        private void IsParameterReferencedAnywhere(ShortGuid id)
        {
            Parallel.ForEach(Entries, comp =>
            {
                Parallel.ForEach(comp.functions, func =>
                {
                    Parallel.ForEach(func.parameters, param =>
                    {
                        if (param.name == id)
                            Console.WriteLine("[" + id + "] " + comp.name + " -> " + Utils.GetEntityName(comp.shortGUID, func.shortGUID) + " -> " + param.name + " [" + param.content.dataType + "]");
                    });
                });
            });
        }

        /// <summary>
        /// Write entity parameters that mirror resource/object bindings (e.g. PhysicsSystem.system_index from the Havok system).
        /// </summary>
        private void SyncDerivedResourceParameters()
        {
            if (Entries == null) return;
            Parallel.ForEach(Entries, comp =>
            {
                if (comp?.functions == null) return;
                foreach (FunctionEntity function in comp.functions)
                {
                    SyncPhysicsSystemIndexParameter(function);
                    SyncEnvironmentMapIndexParameters(function, _textures, _globalTextures);
                }
            });
        }

        /// <summary>
        /// Sets PhysicsSystem.system_index from the bound DYNAMIC_PHYSICS_SYSTEM resource's Havok system index.
        /// </summary>
        private static void SyncPhysicsSystemIndexParameter(FunctionEntity function)
        {
            if (function == null || function.function != FunctionType.PhysicsSystem)
                return;

            ResourceReference resource = function.GetResource(ResourceType.DYNAMIC_PHYSICS_SYSTEM);
            if (resource == null)
                return;

            int index = resource.PhysicsSystem?.SystemIndex ?? resource.PhysicsSystemIndex;
            if (index < 0)
                return;

            SetIntegerParameter(function, ShortGuids.system_index, index);
        }

        /// <summary>
        /// Sets EnvironmentMap Texture_Index / environmentmap_index from the Texture path string.
        /// </summary>
        private static void SyncEnvironmentMapIndexParameters(FunctionEntity function, Textures levelTextures, Textures globalTextures = null)
        {
            if (function == null || function.function != FunctionType.EnvironmentMap)
                return;

            string path = (function.GetParameter(ShortGuids.Texture)?.content as cString)?.value;
            Textures.TEX4 tex = null;
            Textures db = null;
            if (!string.IsNullOrEmpty(path))
            {
                tex = levelTextures?.GetEnvironmentMapByPath(path);
                if (tex != null)
                    db = levelTextures;
                else
                {
                    tex = globalTextures?.GetEnvironmentMapByPath(path);
                    if (tex != null)
                        db = globalTextures;
                }
            }

            int textureIndex = -1;
            int envMapIndex = -1;
            if (tex != null && db != null)
            {
                textureIndex = db.GetWriteIndex(tex);
                envMapIndex = db.GetWriteIndexForEnvMap(tex);
            }

            SetIntegerParameter(function, ShortGuids.Texture_Index, textureIndex);
            SetIntegerParameter(function, ShortGuids.environmentmap_index, envMapIndex);
        }

        private static void SetIntegerParameter(FunctionEntity function, ShortGuid id, int value)
        {
            Parameter param = function.GetParameter(id);
            if (param?.content is cInteger integer)
                integer.value = value;
            else
                function.AddParameter(id, new cInteger(value));
        }
        #endregion
    }
}